"""added rlationships

Revision ID: a62910c3e735
Revises: 61be0da51a92
Create Date: 2025-03-09 22:12:49.011008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62910c3e735'
down_revision: Union[str, None] = '61be0da51a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctors', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'department_id')
    # ### end Alembic commands ###
